### ISSUE TITLE
infinite loading into the community mods

### ISSUE THREAD

**Issue by des3252** [Shmew/MordhauBuddy#1]
## Description
Never loads the community mods and doesn't lets me use local mode installer

## Desktop environment:
 - OS: Win10 
 - Version: 1.4.2

**Comment by Shmew** [comment]
Hi @des3252 can you confirm that the settings page has a full path like this?
![image](https://user-images.githubusercontent.com/11186595/70868942-5a869880-1f4b-11ea-9bc7-635bb20df11f.png)

If not you'll need to find where your Steam installation is and map it like so.

**Comment by des3252** [comment]
> Hi @des3252 can you confirm that the settings page has a full path like this?
> ![image](https://user-images.githubusercontent.com/11186595/70868942-5a869880-1f4b-11ea-9bc7-635bb20df11f.png)
> 
> If not you'll need to find where your Steam installation is and map it like so.

Oh thanks. Sir, that helped me out :)
