### ISSUE TITLE
Continuous Preparing for battle

### ISSUE THREAD

**Issue by GreatBinxi** [Shmew/MordhauBuddy#2]
[MordhauBuddy-Core-2019-12-15T20-52-38Z.log](https://github.com/Shmew/MordhauBuddy/files/3965448/MordhauBuddy-Core-2019-12-15T20-52-38Z.log)

**Comment by Shmew** [comment]
The error is caused by malformed ini data due to how the input.ini keeps track of the console history buffer:

```ini
Failed to parse INI file: Error in Ln: 176 Col: 27
HistoryBuffer=ChangeSize [.1]
                          ^
```

I've created #3 to track this.
