### ISSUE TITLE
Application Hanging

### ISSUE THREAD

**Issue by NathanPrice** [Shmew/MordhauBuddy#5]
[MordhauBuddy-Core-2020-02-05T14-22-54Z.log](https://github.com/Shmew/MordhauBuddy/files/4160025/MordhauBuddy-Core-2020-02-05T14-22-54Z.log)

## Description
Whenever I try to use any of the sections (mordhau configuration for example) and click on the submit option the application will just spin and nothing will happen. I have updated the app, re-installed it, and even whitelisted it through my anti-virus but to no avail so I'm not sure what's going on. I've attached the log file in hops you can see what's going on here. If you need any additional info let me know.

## Desktop environment:
 - OS: Win 10 Enterprise 1809

**Comment by Shmew** [comment]
Talked to @NathanPrice in discord, this was resolved by disabling AV.
