### ISSUE TITLE
Unlimited Loading..

### ISSUE THREAD

**Issue by H8DCarnifeX** [Shmew/MordhauBuddy#6]
## Description
Unlimited "Preparing for Battle"-Loading
No AntiVir nor Firewall tested, no success - still the same
It was running once after install, then never again
i cant use the other buttons, because they are deactivated

## Steps to reproduce
<!-- Steps to reproduce the behavior:
1. just starting the tool

## Expected behavior
i expected the tool to be working

## Screenshots
.

## Desktop environment:
 - OS: Win 7
 - Version: Win 7 Pro SP1

## Additional context
.

**Comment by Shmew** [comment]
Hi!

Can you provide log data so I can take a look?

**Comment by H8DCarnifeX** [comment]
well i would if i just could find a log, was searching for it everywhere to maybe fix it by myself, but had no success finding one

**Comment by Shmew** [comment]
[This page](https://shmew.github.io/MordhauBuddy/reporting-issues.html) should point you in the right direction to find the logs.

**Comment by H8DCarnifeX** [comment]
[MordhauBuddy-Core-2020-03-06T08-49-49Z.log](https://github.com/Shmew/MordhauBuddy/files/4300804/MordhauBuddy-Core-2020-03-06T08-49-49Z.log)

Thank you very much, Shmew!

**Comment by Shmew** [comment]
Looks like it's failing to parse your game.ini file, you can take a look yourself or post it as well. You can find that file here: `C:\Users\<user>\AppData\Local\Mordhau\Saved\Config\WindowsClient`

**Comment by H8DCarnifeX** [comment]
ok here it is
[Game.ini.txt](https://github.com/Shmew/MordhauBuddy/files/4301899/Game.ini.txt)

**Comment by Shmew** [comment]
I was able to get the application to parse your game.ini after finding the malformed line. The last line of your CharacterProfiles there is this stray field that is incorrect:
```ini
GearCustomization=(Wearables=((),(ID=10),(ID=8,Colors=(9,8)),(),(ID=18,Colors=(10,0)),(ID=3,Colors=(7,6),Pattern=2),(ID=4,Colors=(10,0)),(ID=1,Colors=(7,10)),(ID=6,Colors=(7,16))),Equipment=((ID=1,Colors=(9,35,9)),(),())),AppearanceCustomization=(Emblem=31,EmblemColors=(0,0),MetalRoughnessScale=26,MetalTint=4,Age=159,Voice=3,VoicePitch=55,bIsFemale=False,Fat=68,Skinny=133,Strong=138,SkinColor=7,Face=3,EyeColor=4,HairColor=12,Hair=8,FacialHair=1,Eyebrows=0),FaceCustomization=(Translate=(15360,15360,15840,12656,15364,12653,15862,0,15385,0,16320,15847,15855,15855,18703,8690,8683,480,1259,1266,29618,480,480,480,15360,15840,18144,15840,29611,22949,22968,11471,11471,15616,15646,11471,11471,19872,19901,0,0,0,0,0,0,0,0,7665,7660),Rotate=(0,0,0,0,0,0,16,0,0,0,0,14,0,0,12288,591,367,0,15855,15855,18976,0,0,0,0,18432,0,0,18816,0,0,0,0,0,0,0,0,655,335,0,0,15840,15840,0,0,15840,15840,0,0),Scale=(14351,14351,0,15360,0,15360,0,15855,0,15855,14336,0,0,0,14350,0,0,15855,15855,15855,15840,0,15855,15855,0,15914,6,0,15840,0,0,0,0,0,0,0,0,15855,15855,0,0,0,0,0,0,0,0,0,0)),SkillsCustomization=(Perks=40976))
```

Deleting this should let it load.

**Comment by H8DCarnifeX** [comment]
Thanks a lot!
